config/routes.rb
Rails.application.routes.draw do
  resources :cafefeatures
  resources :cafephotos
  resources :wishlistedcafes
  resources :visitedcafe
  resources :blockedcafes
  resources :users
  resources :cafes

end

app/models/cafephoto.rb
class Cafephoto < ActiveRecord::Base
end

app/controllers/cafephotos_controller.rb
class CafephotosController < ApplicationController
  before_action :set_cafephoto, only: [:show, :edit, :update, :destroy]

  # GET /cafephotos
  # GET /cafephotos.json
  def index
    @cafephotos = Cafephoto.all
  end

  # GET /cafephotos/1
  # GET /cafephotos/1.json
  def show
  end

  # GET /cafephotos/new
  def new
    @cafephoto = Cafephoto.new
  end

  # GET /cafephotos/1/edit
  def edit
  end

  # POST /cafephotos
  # POST /cafephotos.json
  def create
    @cafephoto = Cafephoto.new(cafephoto_params)

    respond_to do |format|
      if @cafephoto.save
        format.html { redirect_to @cafephoto, notice: 'Cafephoto was successfully created.' }
        format.json { render :show, status: :created, location: @cafephoto }
      else
        format.html { render :new }
        format.json { render json: @cafephoto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cafephotos/1
  # PATCH/PUT /cafephotos/1.json
  def update
    respond_to do |format|
      if @cafephoto.update(cafephoto_params)
        format.html { redirect_to @cafephoto, notice: 'Cafephoto was successfully updated.' }
        format.json { render :show, status: :ok, location: @cafephoto }
      else
        format.html { render :edit }
        format.json { render json: @cafephoto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cafephotos/1
  # DELETE /cafephotos/1.json
  def destroy
    @cafephoto.destroy
    respond_to do |format|
      format.html { redirect_to cafephotos_url, notice: 'Cafephoto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cafephoto
      @cafephoto = Cafephoto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cafephoto_params
      params.require(:cafephoto).permit(:cafe_id, :photourl)
    end
end

app/helpers/cafephotos_helper.rb
module CafephotosHelper
end

app/views/cafephotos/_form.html.erb
<%= form_for(@cafephoto) do |f| %>
  <% if @cafephoto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cafephoto.errors.count, "error") %> prohibited this cafephoto from being saved:</h2>

      <ul>
      <% @cafephoto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cafe_id %><br>
    <%= f.number_field :cafe_id %>
  </div>
  <div class="field">
    <%= f.label :photourl %><br>
    <%= f.text_field :photourl %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cafephotos/edit.html.erb
<h1>Editing Cafephoto</h1>

<%= render 'form' %>

<%= link_to 'Show', @cafephoto %> |
<%= link_to 'Back', cafephotos_path %>

app/views/cafephotos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cafephotos</h1>

<table>
  <thead>
    <tr>
      <th>Cafe</th>
      <th>Photourl</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cafephotos.each do |cafephoto| %>
      <tr>
        <td><%= cafephoto.cafe_id %></td>
        <td><%= cafephoto.photourl %></td>
        <td><%= link_to 'Show', cafephoto %></td>
        <td><%= link_to 'Edit', edit_cafephoto_path(cafephoto) %></td>
        <td><%= link_to 'Destroy', cafephoto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cafephoto', new_cafephoto_path %>

app/views/cafephotos/new.html.erb
<h1>New Cafephoto</h1>

<%= render 'form' %>

<%= link_to 'Back', cafephotos_path %>

app/views/cafephotos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cafe:</strong>
  <%= @cafephoto.cafe_id %>
</p>

<p>
  <strong>Photourl:</strong>
  <%= @cafephoto.photourl %>
</p>

<%= link_to 'Edit', edit_cafephoto_path(@cafephoto) %> |
<%= link_to 'Back', cafephotos_path %>