config/routes.rb
Rails.application.routes.draw do
  resources :cafefeatures
  resources :cafephotos
  resources :wishlistedcafes
  resources :visitedcafe
  resources :blockedcafes
  resources :users
  resources :cafes

end

app/models/blockedcafe.rb
class Blockedcafe < ActiveRecord::Base
end

app/controllers/blockedcafes_controller.rb
class BlockedcafesController < ApplicationController
  before_action :set_blockedcafe, only: [:show, :edit, :update, :destroy]

  # GET /blockedcafes
  # GET /blockedcafes.json
  def index
    @blockedcafes = Blockedcafe.all
  end

  # GET /blockedcafes/1
  # GET /blockedcafes/1.json
  def show
  end

  # GET /blockedcafes/new
  def new
    @blockedcafe = Blockedcafe.new
  end

  # GET /blockedcafes/1/edit
  def edit
  end

  # POST /blockedcafes
  # POST /blockedcafes.json
  def create
    @blockedcafe = Blockedcafe.new(blockedcafe_params)

    respond_to do |format|
      if @blockedcafe.save
        format.html { redirect_to @blockedcafe, notice: 'Blockedcafe was successfully created.' }
        format.json { render :show, status: :created, location: @blockedcafe }
      else
        format.html { render :new }
        format.json { render json: @blockedcafe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blockedcafes/1
  # PATCH/PUT /blockedcafes/1.json
  def update
    respond_to do |format|
      if @blockedcafe.update(blockedcafe_params)
        format.html { redirect_to @blockedcafe, notice: 'Blockedcafe was successfully updated.' }
        format.json { render :show, status: :ok, location: @blockedcafe }
      else
        format.html { render :edit }
        format.json { render json: @blockedcafe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blockedcafes/1
  # DELETE /blockedcafes/1.json
  def destroy
    @blockedcafe.destroy
    respond_to do |format|
      format.html { redirect_to blockedcafes_url, notice: 'Blockedcafe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blockedcafe
      @blockedcafe = Blockedcafe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blockedcafe_params
      params.require(:blockedcafe).permit(:user_id, :cafe_id)
    end
end

app/helpers/blockedcafes_helper.rb
module BlockedcafesHelper
end

app/views/blockedcafes/_form.html.erb
<%= form_for(@blockedcafe) do |f| %>
  <% if @blockedcafe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blockedcafe.errors.count, "error") %> prohibited this blockedcafe from being saved:</h2>

      <ul>
      <% @blockedcafe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :cafe_id %><br>
    <%= f.number_field :cafe_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blockedcafes/edit.html.erb
<h1>Editing Blockedcafe</h1>

<%= render 'form' %>

<%= link_to 'Show', @blockedcafe %> |
<%= link_to 'Back', blockedcafes_path %>

app/views/blockedcafes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blockedcafes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Cafe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blockedcafes.each do |blockedcafe| %>
      <tr>
        <td><%= blockedcafe.user_id %></td>
        <td><%= blockedcafe.cafe_id %></td>
        <td><%= link_to 'Show', blockedcafe %></td>
        <td><%= link_to 'Edit', edit_blockedcafe_path(blockedcafe) %></td>
        <td><%= link_to 'Destroy', blockedcafe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blockedcafe', new_blockedcafe_path %>

app/views/blockedcafes/new.html.erb
<h1>New Blockedcafe</h1>

<%= render 'form' %>

<%= link_to 'Back', blockedcafes_path %>

app/views/blockedcafes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @blockedcafe.user_id %>
</p>

<p>
  <strong>Cafe:</strong>
  <%= @blockedcafe.cafe_id %>
</p>

<%= link_to 'Edit', edit_blockedcafe_path(@blockedcafe) %> |
<%= link_to 'Back', blockedcafes_path %>