config/routes.rb
Rails.application.routes.draw do
  resources :cafefeatures
  resources :cafephotos
  resources :wishlistedcafes
  resources :visitedcafe
  resources :blockedcafes
  resources :users
  resources :cafes

end

app/models/cafefeature.rb
class Cafefeature < ActiveRecord::Base
end

app/controllers/cafefeatures_controller.rb
class CafefeaturesController < ApplicationController
  before_action :set_cafefeature, only: [:show, :edit, :update, :destroy]

  # GET /cafefeatures
  # GET /cafefeatures.json
  def index
    @cafefeatures = Cafefeature.all
  end

  # GET /cafefeatures/1
  # GET /cafefeatures/1.json
  def show
  end

  # GET /cafefeatures/new
  def new
    @cafefeature = Cafefeature.new
  end

  # GET /cafefeatures/1/edit
  def edit
  end

  # POST /cafefeatures
  # POST /cafefeatures.json
  def create
    @cafefeature = Cafefeature.new(cafefeature_params)

    respond_to do |format|
      if @cafefeature.save
        format.html { redirect_to @cafefeature, notice: 'Cafefeature was successfully created.' }
        format.json { render :show, status: :created, location: @cafefeature }
      else
        format.html { render :new }
        format.json { render json: @cafefeature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cafefeatures/1
  # PATCH/PUT /cafefeatures/1.json
  def update
    respond_to do |format|
      if @cafefeature.update(cafefeature_params)
        format.html { redirect_to @cafefeature, notice: 'Cafefeature was successfully updated.' }
        format.json { render :show, status: :ok, location: @cafefeature }
      else
        format.html { render :edit }
        format.json { render json: @cafefeature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cafefeatures/1
  # DELETE /cafefeatures/1.json
  def destroy
    @cafefeature.destroy
    respond_to do |format|
      format.html { redirect_to cafefeatures_url, notice: 'Cafefeature was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cafefeature
      @cafefeature = Cafefeature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cafefeature_params
      params.require(:cafefeature).permit(:cafe_id, :featurename)
    end
end

app/helpers/cafefeatures_helper.rb
module CafefeaturesHelper
end

app/views/cafefeatures/_form.html.erb
<%= form_for(@cafefeature) do |f| %>
  <% if @cafefeature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cafefeature.errors.count, "error") %> prohibited this cafefeature from being saved:</h2>

      <ul>
      <% @cafefeature.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cafe_id %><br>
    <%= f.number_field :cafe_id %>
  </div>
  <div class="field">
    <%= f.label :featurename %><br>
    <%= f.text_field :featurename %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cafefeatures/edit.html.erb
<h1>Editing Cafefeature</h1>

<%= render 'form' %>

<%= link_to 'Show', @cafefeature %> |
<%= link_to 'Back', cafefeatures_path %>

app/views/cafefeatures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cafefeatures</h1>

<table>
  <thead>
    <tr>
      <th>Cafe</th>
      <th>Featurename</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cafefeatures.each do |cafefeature| %>
      <tr>
        <td><%= cafefeature.cafe_id %></td>
        <td><%= cafefeature.featurename %></td>
        <td><%= link_to 'Show', cafefeature %></td>
        <td><%= link_to 'Edit', edit_cafefeature_path(cafefeature) %></td>
        <td><%= link_to 'Destroy', cafefeature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cafefeature', new_cafefeature_path %>

app/views/cafefeatures/new.html.erb
<h1>New Cafefeature</h1>

<%= render 'form' %>

<%= link_to 'Back', cafefeatures_path %>

app/views/cafefeatures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cafe:</strong>
  <%= @cafefeature.cafe_id %>
</p>

<p>
  <strong>Featurename:</strong>
  <%= @cafefeature.featurename %>
</p>

<%= link_to 'Edit', edit_cafefeature_path(@cafefeature) %> |
<%= link_to 'Back', cafefeatures_path %>