config/routes.rb
Rails.application.routes.draw do
  resources :cafefeatures
  resources :cafephotos
  resources :wishlistedcafes
  resources :visitedcafe
  resources :blockedcafes
  resources :users
  resources :cafes

end

app/models/wishlistedcafe.rb
class Wishlistedcafe < ActiveRecord::Base
end

app/controllers/wishlistedcafes_controller.rb
class WishlistedcafesController < ApplicationController
  before_action :set_wishlistedcafe, only: [:show, :edit, :update, :destroy]

  # GET /wishlistedcafes
  # GET /wishlistedcafes.json
  def index
    @wishlistedcafes = Wishlistedcafe.all
  end

  # GET /wishlistedcafes/1
  # GET /wishlistedcafes/1.json
  def show
  end

  # GET /wishlistedcafes/new
  def new
    @wishlistedcafe = Wishlistedcafe.new
  end

  # GET /wishlistedcafes/1/edit
  def edit
  end

  # POST /wishlistedcafes
  # POST /wishlistedcafes.json
  def create
    @wishlistedcafe = Wishlistedcafe.new(wishlistedcafe_params)

    respond_to do |format|
      if @wishlistedcafe.save
        format.html { redirect_to @wishlistedcafe, notice: 'Wishlistedcafe was successfully created.' }
        format.json { render :show, status: :created, location: @wishlistedcafe }
      else
        format.html { render :new }
        format.json { render json: @wishlistedcafe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wishlistedcafes/1
  # PATCH/PUT /wishlistedcafes/1.json
  def update
    respond_to do |format|
      if @wishlistedcafe.update(wishlistedcafe_params)
        format.html { redirect_to @wishlistedcafe, notice: 'Wishlistedcafe was successfully updated.' }
        format.json { render :show, status: :ok, location: @wishlistedcafe }
      else
        format.html { render :edit }
        format.json { render json: @wishlistedcafe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishlistedcafes/1
  # DELETE /wishlistedcafes/1.json
  def destroy
    @wishlistedcafe.destroy
    respond_to do |format|
      format.html { redirect_to wishlistedcafes_url, notice: 'Wishlistedcafe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wishlistedcafe
      @wishlistedcafe = Wishlistedcafe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wishlistedcafe_params
      params.require(:wishlistedcafe).permit(:user_id, :cafe_id)
    end
end

app/helpers/wishlistedcafes_helper.rb
module WishlistedcafesHelper
end

app/views/wishlistedcafes/_form.html.erb
<%= form_for(@wishlistedcafe) do |f| %>
  <% if @wishlistedcafe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wishlistedcafe.errors.count, "error") %> prohibited this wishlistedcafe from being saved:</h2>

      <ul>
      <% @wishlistedcafe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :cafe_id %><br>
    <%= f.number_field :cafe_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wishlistedcafes/edit.html.erb
<h1>Editing Wishlistedcafe</h1>

<%= render 'form' %>

<%= link_to 'Show', @wishlistedcafe %> |
<%= link_to 'Back', wishlistedcafes_path %>

app/views/wishlistedcafes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Wishlistedcafes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Cafe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wishlistedcafes.each do |wishlistedcafe| %>
      <tr>
        <td><%= wishlistedcafe.user_id %></td>
        <td><%= wishlistedcafe.cafe_id %></td>
        <td><%= link_to 'Show', wishlistedcafe %></td>
        <td><%= link_to 'Edit', edit_wishlistedcafe_path(wishlistedcafe) %></td>
        <td><%= link_to 'Destroy', wishlistedcafe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wishlistedcafe', new_wishlistedcafe_path %>

app/views/wishlistedcafes/new.html.erb
<h1>New Wishlistedcafe</h1>

<%= render 'form' %>

<%= link_to 'Back', wishlistedcafes_path %>

app/views/wishlistedcafes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @wishlistedcafe.user_id %>
</p>

<p>
  <strong>Cafe:</strong>
  <%= @wishlistedcafe.cafe_id %>
</p>

<%= link_to 'Edit', edit_wishlistedcafe_path(@wishlistedcafe) %> |
<%= link_to 'Back', wishlistedcafes_path %>